/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SusanaAlanRouteImport } from './routes/susana-alan'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PriscilaOscarRouteImport } from './routes/priscila-oscar'
import { Route as LuisLeoRouteImport } from './routes/luis-leo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComprarPlataRouteImport } from './routes/comprar.plata'
import { Route as ComprarOroRouteImport } from './routes/comprar.oro'
import { Route as ComprarDiamanteRouteImport } from './routes/comprar.diamante'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ComprarXvPlataRouteImport } from './routes/comprar.xv.plata'
import { Route as ComprarXvOroRouteImport } from './routes/comprar.xv.oro'
import { Route as ComprarXvDiamanteRouteImport } from './routes/comprar.xv.diamante'

const SusanaAlanRoute = SusanaAlanRouteImport.update({
  id: '/susana-alan',
  path: '/susana-alan',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PriscilaOscarRoute = PriscilaOscarRouteImport.update({
  id: '/priscila-oscar',
  path: '/priscila-oscar',
  getParentRoute: () => rootRouteImport,
} as any)
const LuisLeoRoute = LuisLeoRouteImport.update({
  id: '/luis-leo',
  path: '/luis-leo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarPlataRoute = ComprarPlataRouteImport.update({
  id: '/comprar/plata',
  path: '/comprar/plata',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarOroRoute = ComprarOroRouteImport.update({
  id: '/comprar/oro',
  path: '/comprar/oro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarDiamanteRoute = ComprarDiamanteRouteImport.update({
  id: '/comprar/diamante',
  path: '/comprar/diamante',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ComprarXvPlataRoute = ComprarXvPlataRouteImport.update({
  id: '/comprar/xv/plata',
  path: '/comprar/xv/plata',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarXvOroRoute = ComprarXvOroRouteImport.update({
  id: '/comprar/xv/oro',
  path: '/comprar/xv/oro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarXvDiamanteRoute = ComprarXvDiamanteRouteImport.update({
  id: '/comprar/xv/diamante',
  path: '/comprar/xv/diamante',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/luis-leo': typeof LuisLeoRoute
  '/priscila-oscar': typeof PriscilaOscarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/susana-alan': typeof SusanaAlanRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/comprar/diamante': typeof ComprarDiamanteRoute
  '/comprar/oro': typeof ComprarOroRoute
  '/comprar/plata': typeof ComprarPlataRoute
  '/comprar/xv/diamante': typeof ComprarXvDiamanteRoute
  '/comprar/xv/oro': typeof ComprarXvOroRoute
  '/comprar/xv/plata': typeof ComprarXvPlataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/luis-leo': typeof LuisLeoRoute
  '/priscila-oscar': typeof PriscilaOscarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/susana-alan': typeof SusanaAlanRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/comprar/diamante': typeof ComprarDiamanteRoute
  '/comprar/oro': typeof ComprarOroRoute
  '/comprar/plata': typeof ComprarPlataRoute
  '/comprar/xv/diamante': typeof ComprarXvDiamanteRoute
  '/comprar/xv/oro': typeof ComprarXvOroRoute
  '/comprar/xv/plata': typeof ComprarXvPlataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/luis-leo': typeof LuisLeoRoute
  '/priscila-oscar': typeof PriscilaOscarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/susana-alan': typeof SusanaAlanRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/comprar/diamante': typeof ComprarDiamanteRoute
  '/comprar/oro': typeof ComprarOroRoute
  '/comprar/plata': typeof ComprarPlataRoute
  '/comprar/xv/diamante': typeof ComprarXvDiamanteRoute
  '/comprar/xv/oro': typeof ComprarXvOroRoute
  '/comprar/xv/plata': typeof ComprarXvPlataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/luis-leo'
    | '/priscila-oscar'
    | '/reset-password'
    | '/sitemap.xml'
    | '/susana-alan'
    | '/admin'
    | '/comprar/diamante'
    | '/comprar/oro'
    | '/comprar/plata'
    | '/comprar/xv/diamante'
    | '/comprar/xv/oro'
    | '/comprar/xv/plata'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/luis-leo'
    | '/priscila-oscar'
    | '/reset-password'
    | '/sitemap.xml'
    | '/susana-alan'
    | '/admin'
    | '/comprar/diamante'
    | '/comprar/oro'
    | '/comprar/plata'
    | '/comprar/xv/diamante'
    | '/comprar/xv/oro'
    | '/comprar/xv/plata'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/luis-leo'
    | '/priscila-oscar'
    | '/reset-password'
    | '/sitemap.xml'
    | '/susana-alan'
    | '/_authenticated/admin'
    | '/comprar/diamante'
    | '/comprar/oro'
    | '/comprar/plata'
    | '/comprar/xv/diamante'
    | '/comprar/xv/oro'
    | '/comprar/xv/plata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  LuisLeoRoute: typeof LuisLeoRoute
  PriscilaOscarRoute: typeof PriscilaOscarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SusanaAlanRoute: typeof SusanaAlanRoute
  ComprarDiamanteRoute: typeof ComprarDiamanteRoute
  ComprarOroRoute: typeof ComprarOroRoute
  ComprarPlataRoute: typeof ComprarPlataRoute
  ComprarXvDiamanteRoute: typeof ComprarXvDiamanteRoute
  ComprarXvOroRoute: typeof ComprarXvOroRoute
  ComprarXvPlataRoute: typeof ComprarXvPlataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/susana-alan': {
      id: '/susana-alan'
      path: '/susana-alan'
      fullPath: '/susana-alan'
      preLoaderRoute: typeof SusanaAlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priscila-oscar': {
      id: '/priscila-oscar'
      path: '/priscila-oscar'
      fullPath: '/priscila-oscar'
      preLoaderRoute: typeof PriscilaOscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luis-leo': {
      id: '/luis-leo'
      path: '/luis-leo'
      fullPath: '/luis-leo'
      preLoaderRoute: typeof LuisLeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar/plata': {
      id: '/comprar/plata'
      path: '/comprar/plata'
      fullPath: '/comprar/plata'
      preLoaderRoute: typeof ComprarPlataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar/oro': {
      id: '/comprar/oro'
      path: '/comprar/oro'
      fullPath: '/comprar/oro'
      preLoaderRoute: typeof ComprarOroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar/diamante': {
      id: '/comprar/diamante'
      path: '/comprar/diamante'
      fullPath: '/comprar/diamante'
      preLoaderRoute: typeof ComprarDiamanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/comprar/xv/plata': {
      id: '/comprar/xv/plata'
      path: '/comprar/xv/plata'
      fullPath: '/comprar/xv/plata'
      preLoaderRoute: typeof ComprarXvPlataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar/xv/oro': {
      id: '/comprar/xv/oro'
      path: '/comprar/xv/oro'
      fullPath: '/comprar/xv/oro'
      preLoaderRoute: typeof ComprarXvOroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar/xv/diamante': {
      id: '/comprar/xv/diamante'
      path: '/comprar/xv/diamante'
      fullPath: '/comprar/xv/diamante'
      preLoaderRoute: typeof ComprarXvDiamanteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  LuisLeoRoute: LuisLeoRoute,
  PriscilaOscarRoute: PriscilaOscarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SusanaAlanRoute: SusanaAlanRoute,
  ComprarDiamanteRoute: ComprarDiamanteRoute,
  ComprarOroRoute: ComprarOroRoute,
  ComprarPlataRoute: ComprarPlataRoute,
  ComprarXvDiamanteRoute: ComprarXvDiamanteRoute,
  ComprarXvOroRoute: ComprarXvOroRoute,
  ComprarXvPlataRoute: ComprarXvPlataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
